name: PR Large Image Check
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
jobs:
  check-large-images:
    uses: saikiranrko/Central-WF/.github/workflows/large_image_detection.yml@main
    with:
      MAX_IMAGE_SIZE_KB: 80
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
