name: Upload Artifact to Azure

on:
  workflow_dispatch:
    inputs:
      artifact_path:
        description: 'Path to the artifact in JFrog Artifactory'
        required: true
        type: string
        default: 'libs-release-local/com/example/app/1.0.0/test-app-1.0.0.zip'
      azure_fileshare_path:
        description: 'Azure file share directory path (e.g., production/plugins)'
        required: false
        type: string
        default: ''
      overwrite:
        description: 'Whether to overwrite existing files in file share'
        required: false
        type: string
        default: 'true'

jobs:
  call-fileshare-workflow:
  uses: saikiranrko/Central-WF/.github/workflows/upload-artifact-to-fileshare.yml@376bb72f6201bf15293887826a626f236b7310c6
    with:
      artifact_path: ${{ github.event.inputs.artifact_path }}
      azure_fileshare_path: ${{ github.event.inputs.azure_fileshare_path }}
      overwrite: ${{ github.event.inputs.overwrite }}
    secrets:
      ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      AZURE_FILESHARE_SAS_TOKEN_URL: ${{ secrets.AZURE_FILESHARE_SAS_TOKEN_URL }}
