name: Upload Artifact to Azure

on:
  workflow_dispatch:
    inputs:
      artifact_path:
        type: string
        required: true
        default: 'libs-release-local/com/example/app/1.0.0/test-app-1.0.0.zip'
      azure_fileshare_path:
        type: string
        required: false
        default: ''
      overwrite:
        type: string
        required: false
        default: 'true'

jobs:
  call:
    uses: saikiranrko/Central-WF/.github/workflows/upload-artifact-to-fileshare.yml@main
    with:
      artifact_path: ${{ github.event.inputs.artifact_path }}
      azure_fileshare_path: ${{ github.event.inputs.azure_fileshare_path }}
      overwrite: ${{ github.event.inputs.overwrite }}
    secrets:
      ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      AZURE_FILESHARE_SAS_TOKEN_URL: ${{ secrets.AZURE_FILESHARE_SAS_TOKEN_URL }}
